import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import dev from "../public/dev.png";
import Appnswer from "../public/Appnswer.png";
import devMovil from "../public/devMovil.png";
import devData from "../public/devData.png";
import devWeb from "../public/devWeb.png";
import f from "../public/img2.svg";
import gamesData from "../public/GamesData.png";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { GrReactjs } from "react-icons/gr";
import { TbBrandCss3, TbBrandKotlin, TbBrandReactNative } from "react-icons/tb";
import {
  SiJavascript,
  SiFirebase,
  SiPostgresql,
  SiMysql,
  SiTailwindcss,
} from "react-icons/si";
import { DiSqllite } from "react-icons/di";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineHtml5,
  AiFillAndroid,
} from "react-icons/ai";
import Lottie from "lottie-react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Julian Salas Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <header className="fixed  top-0  left-0 right-0 bg-gray-200  dark:bg-gray-800 ">
        <nav className=" px-10 flex justify-between flex-wrap  ">
          <div className="flex mb-5 gap-3 items-center">
            <Lottie
              animationData={require("../public/82423-developer-yoga.json")}
              autoPlay={true}
              rendererSettings={{ preserveAspectRatio: "xMidYMid slice" }}
              loop={true}
              style={{
                marginLeft: "auto",
                marginRight: "auto",
                width: 60,
                height: 60,
                marginTop: 0,
              }}
            />
            <h1 className="text-xl font-burtons dark:text-white ">Julians</h1>
          </div>

          <ul className="flex items-center justify-between ">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl dark:text-white"
              />
            </li>
            <li>
              <a
                className="text-xl font-burtons dark:text-white  px-4 "
                href="#resumen"
              >
                Resumen
              </a>
            </li>
            <li>
              <a
                className="text-xl font-burtons dark:text-white  px-4 "
                href="#habilidades"
              >
                Habilidades
              </a>
            </li>
            <li>
              <a
                className="text-xl font-burtons dark:text-white  px-4 "
                href="#portafolio"
              >
                Portafolio
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <main className="bg-white dark:bg-gray-900 ">
        <section className=" pt-32 bg-gray-200 dark:bg-gray-900 " id="resumen">
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-900 font-medium dark:text-teal-400 md:text-6xl">
              Julian Salas
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Ingeniero de Sistemas
            </h3>
            <p className="text-md py-5 leading-8 text-gray-900 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Soy un entusiasta por el diseño y desarrollo de sistemas
              informáticos, con 2 años de experiencia en diferentes lenguajes de
              programación y tecnologías.
            </p>

            <p className="text-md py-5 leading-8 text-gray-900 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Me apasiona estar al día con las últimas tendencias y avances
              tecnológicos, y me gusta compartir mi conocimiento y experiencia
              con otros desarrolladores y estudiantes.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16  text-slate-700 dark:text-gray-400">
            <a
              href="https://www.linkedin.com/in/juli%C3%A1n-salas-0aba8122a/"
              target="_blank"
            >
              <AiFillLinkedin className="hover:-translate-y-1 cursor-pointer" />
            </a>
            <a href="https://github.com/julians25" target="_blank">
              <AiFillGithub className="hover:-translate-y-1  cursor-pointer" />
            </a>
          </div>
          <div className="w-full -bottom-40 bg-gray-200">
            <Image alt="" src={darkMode ? "" : f} />
          </div>
        </section>

        <section className="py-10 md:px-20 lg:px-40" id="habilidades">
          <h3 className="text-3xl my-8 dark:text-white">Habilidades</h3>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg h-96 rounded-xl  bg-gray-100 dark:bg-gray-800 flex-1">
              <div className=" mx-auto bg-gradient-to-b from-gray-200 dark:bg-gradient-to-b dark:from-gray-900   w-40 h-40 mt-10">
                <Image src={devWeb} alt={""} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Desarrollo Web
              </h3>
              <h4 className="py-4 text-teal-600">Herramientas</h4>
              <div className="text-4xl flex justify-center gap-10  text-slate-700 dark:text-gray-400">
                <AiOutlineHtml5
                  className="hover:-translate-y-1  cursor-pointer"
                  title="HTML5"
                />
                <TbBrandCss3
                  className="hover:-translate-y-1  cursor-pointer"
                  title="CSS"
                />
                <GrReactjs
                  className="hover:-translate-y-1  cursor-pointer"
                  title="React js"
                />
                <SiJavascript
                  className="hover:-translate-y-1  cursor-pointer"
                  title="Javascript"
                />
              </div>
            </div>
            <div className="text-center shadow-lg h-96 rounded-xl mb-24 bg-gray-100 dark:bg-gray-800 flex-1">
              <div className=" mx-auto bg-gradient-to-b from-gray-200 dark:bg-gradient-to-b dark:from-gray-900  w-40 h-40 mt-10">
                <Image src={devMovil} alt={""} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Desarrollo móvil
              </h3>
              <h4 className="py-4 text-teal-600">Herramientas</h4>
              <div className="text-4xl flex justify-center gap-10  text-slate-700 dark:text-gray-400">
                <AiFillAndroid
                  className="hover:-translate-y-1  cursor-pointer"
                  title="AndroidStudio"
                />
                <TbBrandReactNative
                  className="hover:-translate-y-1  cursor-pointer"
                  title="React Native"
                />
                <TbBrandKotlin
                  className="hover:-translate-y-1  cursor-pointer"
                  title="kotlin"
                />
                <SiJavascript
                  className="hover:-translate-y-1  cursor-pointer"
                  title="java"
                />
              </div>
            </div>
            <div className="text-center shadow-lg h-96 rounded-xl mb-24 bg-gray-100 dark:bg-gray-800 flex-1">
              <div className=" mx-auto bg-gradient-to-b from-gray-200 dark:bg-gradient-to-b dark:from-gray-900  w-40 h-40 mt-10">
                <Image src={devData} alt={""} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                Bases de Datos
              </h3>
              <h4 className="py-4 text-teal-600">Herramientas</h4>
              <div className="text-4xl flex justify-center gap-10  text-slate-700 dark:text-gray-400">
                <SiFirebase
                  className="hover:-translate-y-1  cursor-pointer"
                  title="FireBase"
                />
                <SiPostgresql
                  className="hover:-translate-y-1  cursor-pointer"
                  title="Postgresql"
                />
                <SiMysql
                  className="hover:-translate-y-1  cursor-pointer"
                  title="Mysql"
                />
                <DiSqllite
                  className="hover:-translate-y-1  cursor-pointer"
                  title="SqlLitte"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-10 md:px-20 lg:px-40" id="portafolio">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portafolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Durante mi carrera profesional, he tenido la oportunidad de
              trabajar en diversos proyectos de software, desde el diseño y
              creacion de bases de datos hasta el desarrollo de aplicaciones web
              y móviles. Me considero un desarrollador polifacético, capaz de
              adaptarme a diferentes lenguajes de programación y entornos de
              desarrollo.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap text-center">
            <div className="basis-1/3 flex-1 ">
              <a href="https://appnswer-ba06b.firebaseapp.com/" target="_blank">
                <Image
                  className="rounded-lg object-cover"
                  alt=""
                  src={Appnswer}
                />
              </a>
              <h1 className="text-2xl py-1 dark:text-white font-burtons">
                Appnswer
              </h1>
              <div className="text-4xl flex justify-center gap-10  text-slate-700 dark:text-gray-400">
                <SiFirebase
                  className="hover:-translate-y-1  cursor-pointer"
                  title="FireBase"
                />
                <TbBrandReactNative
                  className="hover:-translate-y-1  cursor-pointer"
                  title="React Native"
                />
                <TbBrandCss3
                  className="hover:-translate-y-1  cursor-pointer"
                  title="Css3"
                />
              </div>
            </div>

            <div className="basis-1/3 flex-1">
              <a href="https://gamesdata-3eb60.web.app/" target="_blank">
                <Image
                  className="rounded-lg object-cover cursor-pointer"
                  alt=""
                  src={gamesData}
                />
              </a>
              <h1 className="text-2xl py-1 dark:text-white font-burtons">
                GamesData
              </h1>
              <div className="text-4xl flex justify-center gap-10  text-slate-700 dark:text-gray-400">
                <GrReactjs
                  className="hover:-translate-y-1  cursor-pointer"
                  title="React js"
                />
                <TbBrandCss3
                  className="hover:-translate-y-1  cursor-pointer"
                  title="Css3"
                />
                <SiJavascript
                  className="hover:-translate-y-1  cursor-pointer"
                  title="Javacript"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-10 md:px-20 lg:px-96" id="contacto">
          <div className=" bg-gray-200  dark:bg-gray-800 ">
            <div className="text-center align-middle ">
              <h2 className="text-3xl pt-4 dark:text-white font-burtons ">
                Contacto
              </h2>
            </div>

            <div className="flex flex-col justify-center gap-10 lg:flex-row lg:flex-wrap">
              <div className=" bg-gray-200  dark:bg-gray-800 px-8 lg:px-0 lg:py-8 ">
                <p>
                  <strong>Email:</strong> juliansant25@gmail.com
                </p>
                <p>
                  <strong>Instagram</strong> julians25_ig
                </p>
                <div className=" hidden lg:block">
                  <Lottie
                    animationData={require("../public/39021-copying-data-web-developer-typing-on-computer.json")}
                    autoPlay={true}
                    rendererSettings={{ preserveAspectRatio: "xMidYMid slice" }}
                    loop={true}
                    style={{
                      marginLeft: "auto",
                      marginRight: "auto",
                      width: 160,
                      height: 160,
                      marginTop: 50,
                    }}
                  />
                </div>
              </div>

              <form
                name="contact"
                method="POST"
                data-netlify="true"
              >
                <input type="hidden" name="form-name" value="contact"/>
                <div className="  flex flex-col dark:bg-gray-800 p-8 ">
                  <label className="font-poppins font-bold">
                    Nombre
                  </label>
                  <input
                    required
                    type="text"
                    name="nombre"
                    className="shadow-sm shadow-black bg-slate-100 mb-2"
                  />
                  <label  className="font-poppins font-bold">
                    Email
                  </label>
                  <input
                    required
                    type="email"
                    name="correo"
                    className="shadow-sm shadow-black bg-slate-100 mb-2"
                  />
                  <label  className="font-poppins font-bold">
                    Mensaje
                  </label>
                  <textarea
                    required
                    name="mensaje"
                    cols={30}
                    rows={10}
                    className="shadow-sm shadow-black bg-slate-100"
                  />
                  <div className="flex justify-center">
                    <button
                      type="submit"
                      className="mt-4 bg-cyan-700 text-white px-4 rounded-md ml-8 py-2"
                    >
                      Enviar
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
